name: Publish docs via GitHub Pages
on:
  workflow_run:
    workflows: ["Bump version"]  # the name: in bumpversion.yml, not the filename
    branches: [main]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.MKDOCS_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
